spring:
  application:
    name: um
  datasource:
    url: "${JDBC_DATABASE_URL}"
    username: "${JDBC_DATABASE_USERNAME}"
    password: "${JDBC_DATABASE_PASSWORD}"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: "${spring.flyway.schemas}"
        jdbc.lob.non_contextual_creation: true # fixes clob creation exception
  flyway:
    schemas: todarch_um
  rabbitmq:
    host: "${RABBITMQ_HOST}"
    port: "${RABBITMQ_PORT}"
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
  cloud:
    stream:
      bindings: # use lower case binding names, contract verifier looks for lower-cased bean name
        emailbinding: # @Output("emailbinding")
          destination: emails # exchange name, no usage in code

todarch.healtcheck.endpoints.enabled: true
